config/routes.rb
Rails.application.routes.draw do
  resources :import_columns_definitions do
    collection do
      post :analyze_csv, to: "csv_analyses#create"
    end
  end

  resources :import_matchers
  resources :categories

  resources :accounts do
    resources :transactions, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :bank_accounts, controller: :accounts
  resources :credit_card_accounts, controller: :accounts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "accounts#index"
end

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div id="notice_explanation">
    <h2><%= notice %></h2>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Our Accounts" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <nav>
    <div class="pure-menu pure-menu-horizontal">
      <ul class="pure-menu-list">
        <li class="pure-menu-item">
          <%= link_to 'Accounts', accounts_path, class: "pure-menu-link" %>
        </li>
        <li class="pure-menu-item">
          <%= link_to 'Categories', categories_path, class: "pure-menu-link" %>
        </li>
        <li class="pure-menu-item">
          <%= link_to 'Input Columns Definition', import_columns_definitions_path, class: "pure-menu-link" %>
        </li>
        <li class="pure-menu-item">
          <%= link_to 'Import Matcher', import_matchers_path, class: "pure-menu-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>